version: '3'

services:
  
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: asky
    ports:
      - "5432:5432"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
 
  users:
    build: ./users
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: "postgresql+asyncpg://postgres:postgres@postgres/asky"
      GATEWAY_URL: "http://gateway:80"
    depends_on:
      postgres:
        condition: service_healthy

  images:
    build: ./image_processor
    ports:
      - "8002:8002"
    environment:
      DATABASE_URL: "postgresql+asyncpg://postgres:postgres@postgres/asky"
      GATEWAY_URL: "http://gateway:80"
    depends_on:
      postgres:
        condition: service_healthy

  gateway:
    build: ./gateway
    ports:
      - "8000:80"
    depends_on: 
      - users
      - images

volumes:
  postgres_data: